AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: "Test Project"

Resources:
  MyFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: getOrders/getOrders.py
      Handler: getOrders.handler
      Runtime: python3.7
